@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant " "
participant TrackController as CTRL
participant TrackService as SERV
participant TrackRepository as REPO
participant TrackAssembler as ASSEMBLER


" "-> CTRL: getTracks()
activate CTRL

CTRL -> SERV: getTracks()
activate SERV

SERV -> REPO: findAll()
activate REPO

REPO --> SERV: tracks
deactivate REPO

SERV --> CTRL: tracks
deactivate SERV

CTRL -> ASSEMBLER: toDTO(tracks)
activate ASSEMBLER

ASSEMBLER --> CTRL: tracksDTO
deactivate ASSEMBLER

CTRL --> " ": tracksDTO
deactivate CTRL

@enduml