@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant " "
participant ":VehicleController" as CTRL
participant VehicleParametersUtils as VehicleParametersUtils
participant "vehicleParameters:VehicleParameters" as vehicleParameters
participant ":VehicleService" as SERV
participant ":VehicleFactory" as FACTORY
participant ":VehicleRepository" as REPO
participant ":VehicleAssembler" as ASSEMBLER


" " -> CTRL: createVehicle(vehicleDataInDTO)
activate CTRL

CTRL -> VehicleParametersUtils: getVehicleParameters(vehicleDataInDTO)
activate VehicleParametersUtils

create vehicleParameters
VehicleParametersUtils -> vehicleParameters: vehicleParameters
activate vehicleParameters

vehicleParameters --> VehicleParametersUtils: vehicleParameters
deactivate vehicleParameters

VehicleParametersUtils --> CTRL: vehicleParameters
deactivate VehicleParametersUtils

CTRL -> SERV: createVehicle(vehicleParameters)
activate SERV

SERV -> FACTORY: create(vehicleParameters)
activate FACTORY

FACTORY -> SERV: vehicle
deactivate FACTORY

SERV -> REPO: save(vehicle)
activate REPO

REPO --> SERV: vehicle
deactivate REPO

SERV -> ASSEMBLER: toDTO(vehicle)
activate ASSEMBLER

ASSEMBLER --> SERV: vehicleDataOutDTO
deactivate ASSEMBLER

SERV --> CTRL: vehicleDataOutDTO
deactivate SERV

CTRL --> " ": vehicleDataOutDTO
deactivate CTRL

@enduml