### Create simulations
POST http://localhost:8080/simulations
Content-Type: application/json

{
  "simulationName": "Simulation 1",
  "vehicleID": "3f4e0326-f349-4b22-8b35-77c72706fd55",
  "trackID": "15178dbe-a534-4fa4-8c94-43517897d380"
}

###

POST http://localhost:8080/simulations
Content-Type: application/json

{
  "simulationName": "Simulation 2",
  "vehicleID": "930249r",
  "trackID": "621245c1-7937-4ff5-82b3-fde1ce6b0e7a"
}

###

POST http://localhost:8080/simulations
Content-Type: application/json

{
  "simulationName": "Simulation 3",
  "vehicleID": "324fwerwer",
  "trackID": "0f9f5a2e-abbb-4082-8a7b-74eb8812ebf9"
}

###

