%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gonca\CLionProjects\untitled11\output.csv
%
% Auto-generated by MATLAB on 11-Jun-2024 23:11:32

fname = 'simulationData.json'; 
fid = fopen(fname); 
raw = fread(fid,inf); 
str = char(raw'); 
fclose(fid); 
val = jsondecode(str);

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";


ax = axes; hold(ax,'on');
colormap(ax,"winter");


% val.track.trackName = ''
val.track.trackName = 'Spain_racingline.track';
k = 1;
c = colormap(cool);

for i=0:-0.1:-2.6
    val.vehicle.sCx = i;
    valencoded = jsonencode(val);
    fid = fopen('simulationData.json','w');
    fprintf(fid,'%s',valencoded);
    fclose(fid);

    system('cmake-build-debug-visual-studio\cpp simulationData.json');

    % Import the data
    output = readtable("output.csv", opts);

    % Convert to output type
    output = table2array(output);
    
    % Clear temporary variables


    % ax1 = subplot(2,1,1);
    grid minor
    
    plot(ax,output(:,1), output(:,2)*3.6);

    k = k + 5;
% plot(output(:,2)); hold on
% ax2 = subplot(2,1,2);
% plot(output(:,2));
% linkaxes([ax1, ax2],'x');

end

%% 
% syms v c muy m g cz rho 
% 
% eq = v^2*c == muy/m * (m*g + 1/2*cz*rho*v^2);
% sol = solve(eq,v);


%%
% outFilt = smooth(output,10);
% 
% plot(outFilt);



% PEng = 80000;
% cx = 0.9;
% c = output;
% cz = 1;
% m = 1000;
% muy = 1;
% g = 9.81;
% rho = 1.3;
% 
% vMax = (PEng*2/(cx*rho))^(1/3);
% 
% v1 = min(sqrt(g*muy./c),vMax);
% v2 = min(sqrt(2*m*muy*g./(2*m*c) - (cz*rho*muy)), vMax);
% v3 = -(2^(1/2)*m*((g*muy*(2.*c*m - cz*muy*rho))/m).^(1/2))./(2.*c*m - cz*muy*rho);
% v4 = sqrt(-(muy*m*g)./(muy*1/2*cz*rho - m.*c));
% v4(imag(v4)~=0) = vMax;
% v4 = real(v4);
% 
% plot(v1); hold on
% plot(v2); hold on
% plot(v4);

%%




