@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
participant Frontend
participant Server
participant Database

User -> Frontend: I want to update a vehicle
activate Frontend

Frontend -> Server: updateVehicle(vehicleID, vehicleDataInDTO)
activate Server

Server -> Database: SELECT * FROM vehicles WHERE id = vehicleID
activate Database

Database --> Server: vehicleDataModel
deactivate Database

Server --> Database: UPDATE vehicles SET ... WHERE id = vehicleID
activate Database

Database --> Server: vehicleDataModel
deactivate Database

Server --> Frontend: vehicleDataOutDTO
deactivate Server

Frontend --> User: vehicleDataOutDTO
deactivate Frontend

@enduml